/**
 * createOutgoingCallRoom — creates the persisted call session for an
 * outgoing call.
 *
 * Identity (one stable id end to end):
 *   callId    = call_history.id          — generated here, sent in the INSERT
 *   sessionId = call_history.session_id  — generated by the database; every
 *               signaling message for this call must carry it
 *   roomName  = `duo-call-<callId>`      — derived; livekit-token derives the
 *               identical value server-side and never trusts a stored name
 *
 * Ordering: livekit-token authorizes by looking the call up by id, so the
 * call_history row MUST exist before joinCall() fetches a token.
 */
import { roomNameForCall } from "@/lib/signalingEngine/types";
import { newUuid } from "./ids";
import type { CallEngineProviderId } from "./types";

export interface OutgoingCallRoomSelfHosted {
  provider: "self_hosted";
  /** The call_history row's own id — SelfHostedCallEngineAdapter.joinCall
   *  expects this as its first argument, not a URL. */
  roomId: string;
  /** call_history.session_id — DB-generated, the authoritative session
   *  identity every signaling message for this call must carry. */
  sessionId: string;
  /** Derived room: `duo-call-<callId>`. The livekit-token function derives
   *  the identical value itself and never trusts a stored room name. */
  roomName: string;
}

export type OutgoingCallRoomResult = OutgoingCallRoomSelfHosted;

export interface CreateOutgoingCallRoomOptions {
  userId: string;
  /** Inserts the call_history row; awaited before anything else. */
  insertCallHistoryForSelfHosted?: (row: { callId: string; roomName: string }) => Promise<{ id: string; sessionId: string }>;
  timeoutMs?: number;
}

export async function createOutgoingCallRoom(
  provider: CallEngineProviderId,
  opts: CreateOutgoingCallRoomOptions,
): Promise<OutgoingCallRoomResult> {
  if (!opts.insertCallHistoryForSelfHosted) {
    // Programmer error, not a runtime/network failure — fail loudly rather
    // than silently falling back to a provider the caller didn't ask for.
    throw new Error("createOutgoingCallRoom: self_hosted requires insertCallHistoryForSelfHosted");
  }
  // PHASE 4: the call id is minted here (so the room name can be derived
  // from it and stored in the same INSERT) and the DATABASE is the
  // authority on it: if the returned row's id differs, something is wrong
  // and the call must not proceed. The room name is `duo-call-<callId>` —
  // deterministic and server-verifiable — instead of a client-invented
  // string the livekit-token function would have had to trust.
  const callId = newUuid();
  const roomName = roomNameForCall(callId);
  const row = await opts.insertCallHistoryForSelfHosted({ callId, roomName });
  if (row.id !== callId) throw new Error("createOutgoingCallRoom: call_history returned a different id than requested");
  if (!row.sessionId) throw new Error("createOutgoingCallRoom: call_history returned no session_id (migration 20260920130000 not applied?)");
  return { provider: "self_hosted", roomId: row.id, sessionId: row.sessionId, roomName };
}
