// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { isOnlineNow } from '../../lib/connectivity';

// BLANK-SCREEN FIX: `createClient()` throws synchronously ("supabaseUrl is
// required.") if its first two args are falsy. That throw happens while
// THIS MODULE is being evaluated — i.e. before main.tsx's own top-level code
// runs, since ES module imports are evaluated before the importing module's
// body (App.tsx imports this file, main.tsx imports App.tsx). An import-time
// throw isn't a render-time error, so <ErrorBoundary> can't catch it either —
// the whole script just aborts and the page is left blank with nothing but a
// console error.
//
// This used to happen whenever VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY
// weren't set at build time — which turned out to be inconsistent across every
// place this project actually runs: Lovable's own hosting injects them
// automatically, but a local `npm run dev` needs a `.env` Vite picks up at
// *startup* (a stale running dev server or cache won't see a newly-added one),
// and Vercel/Netlify/Cloudflare Pages need them set in that host's own
// dashboard before a build, not read from anything shipped in the repo/zip.
// Three different platforms, three different places to configure the same
// two values — too easy for one of them to be missing.
//
// Real fix: stop depending on env vars being configured at all. The anon/
// publishable key below is meant to be public in a client bundle by design —
// it's not the service_role key, and this project's Row Level Security
// policies are what actually protect data, the same way they would if this
// value were read from an env var instead. So it's hardcoded as the default,
// with env vars only as an *override* (e.g. pointing a build at a different
// Supabase project later) rather than a requirement. This makes the app work
// out of the box on Lovable, Vercel, and local — no platform-specific setup
// step required — while still respecting VITE_SUPABASE_URL /
// VITE_SUPABASE_PUBLISHABLE_KEY if you ever do set them.
const DEFAULT_SUPABASE_URL = "https://jzlpelxwzjjpddqcrtpu.supabase.co";
const DEFAULT_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_1ZGx52jJok6cITi8Ky3ifQ_TtOErEac";

const SAFE_URL = import.meta.env.VITE_SUPABASE_URL || DEFAULT_SUPABASE_URL;
const SAFE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || DEFAULT_SUPABASE_PUBLISHABLE_KEY;

// Kept for any code checking this — always true now that there's a working
// default, but preserved as a named export so main.tsx's setup-screen branch
// still compiles/behaves sanely if a future change ever clears the defaults.
export const isSupabaseConfigured = Boolean(SAFE_URL && SAFE_KEY);
export const SUPABASE_URL_PUBLIC = SAFE_URL;
export const SUPABASE_KEY_PUBLIC = SAFE_KEY;

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

// PGRST303-FIX: "Couldn't save profile" / any freshly-signed-in write failing
// with { code: "PGRST303", message: "JWT issued at future" }.
//
// This is NOT a client clock problem (confirmed: device clock, session,
// and token iat are all correct in every report of this). It's a known,
// ongoing Supabase platform bug: PostgREST caches its notion of "now" via a
// libev/mkAutoUpdate timer, and on the very first request over a freshly
// opened connection that cache can still be a stale/unpopulated value —
// enough for a token minted a moment ago to look like it's "from the
// future" to the validator. Upstream tracked as PostgREST/postgrest#5196
// (postgrest#5159 was a related-but-different fix that didn't fully cover
// this path); Supabase's own incident (status.supabase.com/incidents/
// bv4ntm4x0btf) rolled hosted projects back to a pinned PostgREST 14.5
// specifically over this and a second issue in newer builds, so as of this
// writing there's no client-side way to "fix" the root cause — Supabase
// support's own guidance is that a short retry clears it, since only the
// first request on a fresh connection/right after token mint is affected
// and the identical token succeeds moments later.
//
// So: retry transparently, here, for every Supabase call this app makes
// (Data API + Edge Functions), instead of leaving it to bubble up as
// "Couldn't save profile" (or any other write) with no recovery. Safe to
// retry blindly because the original request never reached the database —
// it was rejected by PostgREST's auth layer before doing anything.
const PGRST303_MAX_RETRIES = 3;
const PGRST303_BASE_DELAY_MS = 350;

function isPgrst303Body(text: string): boolean {
  if (!text) return false;
  // Cheap pre-check before bothering to JSON.parse.
  if (text.indexOf('PGRST303') === -1 && text.indexOf('issued at future') === -1) return false;
  try {
    const parsed = JSON.parse(text);
    return parsed?.code === 'PGRST303' || /issued at future/i.test(parsed?.message ?? '');
  } catch {
    return /PGRST303|issued at future/i.test(text);
  }
}

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

// OFFLINE-FIRST (2026-09-21): two guards so the app never sits waiting on a
// network that isn't there.
//
// 1. Definitely offline (airplane mode, no radio): fail immediately instead of
//    handing the request to the OS to time out. supabase-js turns a rejected
//    fetch into an ordinary { error } (PostgREST) / AuthRetryableFetchError
//    (auth), exactly what a real connectivity failure looks like, so every
//    caller's existing error handling applies unchanged. It also stops the
//    auth client from spending its long refresh backoff on requests that
//    cannot possibly succeed.
// 2. "Connected" to Wi-Fi with a dead uplink (navigator.onLine can't tell):
//    a plain data READ (GET/HEAD on /rest/v1/) gets a hard ceiling so a
//    loading spinner resolves into an error/cached state instead of hanging
//    for the OS's own multi-minute TCP timeout. Only reads are capped — a
//    write that is aborted client-side may still have reached the server, and
//    uploads/edge functions legitimately run long.
const REST_READ_TIMEOUT_MS = 25_000;

function withReadTimeout(url: unknown, init: RequestInit): { init: RequestInit; done: () => void } {
  const method = (init.method ?? 'GET').toUpperCase();
  if ((method !== 'GET' && method !== 'HEAD') || !String(url).includes('/rest/v1/')) {
    return { init, done: () => {} };
  }
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), REST_READ_TIMEOUT_MS);
  const outer = init.signal;
  if (outer) {
    if (outer.aborted) controller.abort();
    else outer.addEventListener('abort', () => controller.abort(), { once: true });
  }
  return { init: { ...init, signal: controller.signal }, done: () => clearTimeout(timer) };
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);

    // Normalize to a plain (url, init) pair so the retry loop below can
    // safely re-issue the same request: a `Request` instance's body can
    // only be read/consumed once, so retrying `fetch(input, ...)` a second
    // time with the original Request would throw. supabase-js always calls
    // fetch with a plain URL + string body in practice, but fold a Request
    // instance's own method/body into requestInit too, just in case.
    const url = typeof Request !== 'undefined' && input instanceof Request ? input.url : input;
    const requestInit: RequestInit = { ...init, headers };
    if (typeof Request !== 'undefined' && input instanceof Request) {
      requestInit.method ??= input.method;
      if (requestInit.body === undefined && input.body) {
        requestInit.body = await input.clone().text();
      }
    }

    let attempt = 0;
    for (;;) {
      if (!isOnlineNow()) throw new TypeError('Failed to fetch');
      const timed = withReadTimeout(url, requestInit);
      let response: Response;
      try {
        response = await fetch(url, timed.init);
      } finally {
        // Headers are in (or the request failed): the ceiling has done its job.
        timed.done();
      }

      // Only ever worth inspecting/retrying on a 401 — every other status
      // (including a real success) skips the body read entirely.
      if (response.status !== 401 || attempt >= PGRST303_MAX_RETRIES) {
        return response;
      }

      // Body can only be consumed once — clone before reading so we can
      // still hand the original (or an equivalent) response back untouched
      // if this turns out not to be the error we're looking for.
      const text = await response.clone().text();
      if (!isPgrst303Body(text)) {
        return response;
      }

      attempt += 1;
      const jitter = Math.random() * 150;
      await sleep(PGRST303_BASE_DELAY_MS * 2 ** (attempt - 1) + jitter);
      // loop: re-issue the identical request
    }
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SAFE_URL, SAFE_KEY, {
  global: {
    fetch: createSupabaseFetch(SAFE_KEY),
  },
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
